<?php

namespace Acme\UserBundle\Entity;

/**
 * SymbolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymbolRepository extends \Doctrine\ORM\EntityRepository
{


}
