# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    acme.user.service.trendline_builder:
        class: AppBundle\Service\TrendlineBuilder
        arguments: ["@acme.yahoo.dataprovider.finance.historicaldata"]


    acme.yahoo.query.adapter:
        class: AppBundle\Query\Adapter\Adapter

    acme.yahoo.query.builder:
        class: AppBundle\Query\Builder\Builder
        arguments: ["@acme.yahoo.query.adapter"]

    acme.yahoo.dataprovider.finance.historicaldata:
        class: AppBundle\DataProvider\Finance\History
        arguments: ["@acme.yahoo.query.builder"]