# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    acme.yahoo.query.base_url: "http://query.yahooapis.com/v1/public/yql"

services:
    acme.yahoo.query.adapter:
        class: Acme\YahooBundle\Query\Adapter\Adapter

    acme.yahoo.query.builder:
        class: Acme\YahooBundle\Query\Builder\Builder
        arguments: ["@acme.yahoo.query.adapter"]

    acme.yahoo.dataprovider.finance.historicaldata:
        class: Acme\YahooBundle\DataProvider\Finance\History
        arguments: ["@acme.yahoo.query.builder"]
